namespace UWPApp
{
	[default_interface]
	runtimeclass ReactNativeWinRT : Windows.UI.Xaml.Controls.UserControl
	{
	  ReactNativeWinRT();
      Windows.UI.Xaml.Controls.Grid ReactRootView{ get; };
	}
}
